version: '2'
services:
  api:
    container_name: weedlabs_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
      - "4567:4567"
    volumes:
      - .:/opt/api
      - bundle:/usr/local/bundle
    tty: true
    command: bash -c "cd api && bundle install --jobs 3 && bundle exec rake"
  app:
    container_name: weedlabs_app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/opt/app
    command: bash -c "cd app && polymer init polymer-2-starter-kit && polymer serve --open -p 8081"
volumes:
  bundle:
    driver: local
